name: JavaScript files

on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: yarn
      - name: Generate clients
        run: yarn generate
