name: Update client libraries

on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Configure github credentials
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Install dependencies
        run: yarn
      - name: Generate clients
        run: yarn generate
      - name: Build clients
        run: yarn build-clients
      - name: Checkout TS Client repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: kuskoman/h1-client-ts
          path: h1-client-ts
      - name: Copy TS client
        run: /bin/cp -rf ./clients/ts/. h1-client-ts
      - name: Commit TS client
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Update $(date)"
        working-directory: h1-client-ts
      - name: Push TS client
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          directory: h1-client-ts
          repository: kuskoman/h1-client-ts
