name: JavaScript files

on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn
      - name: Generate clients
        run: yarn generate
      - name: Configure github credentials
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Checkout TS Client repo
        uses: actions/checkout@v2
        with:
          repository: kuskoman/h1-client-ts
          path: h1-client-ts
      - name: Copy TS client
        run: /bin/cp -rf ./clients/ts/. h1-client-ts
      - name: Install dev dependencies for TS client
        run: yarn
      - name: Transpile TS client
        run: yarn build
        working-directory: h1-client-ts
      - name: Commit TS client
        run: |
          git fetch --unshallow origin
          git add .
          git commit -m "Update $(date)"
        working-directory: h1-client-ts
      - name: Push TS client
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: h1-client-ts
          force: true
